<a href="https://colab.research.google.com/github/HaziqKhilmi/data-science-toolkit/blob/main/tutorial03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Tutorial 3**
Muhammad Haziq bin Mohammad Khilmi (23001806)

Question 1

In [3]:
import numpy as np
a= np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


Question 2

In [8]:
b=np.random.randint(0,10,size=[3,4])
print(b)

[[1 2 6 7]
 [3 5 4 9]
 [4 8 8 0]]


Question 3

In [12]:
c=np.ones((2,2))
d=np.zeros((3,3))
print(c)
print()
print(d)

[[1. 1.]
 [1. 1.]]

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Question 4

In [17]:
e=np.random.randint(0,100,size=[6,3])
print('Original array')
print(e)
print()
print('Transposed array')
f=np.transpose(e)
print(f)

Original array
[[30 37 87]
 [64 69 42]
 [ 4 59 96]
 [90 45 49]
 [59 53 89]
 [16 41 92]]

Transposed array
[[30 64  4 90 59 16]
 [37 69 59 45 53 41]
 [87 42 96 49 89 92]]


Question 5

In [21]:
g=np.random.randint(0,100,size=[3,2])
h=np.random.randint(0,100,size=[2,4])
i=np.dot(g,h)
print('Array 1')
print(g)
print()
print('Array 2')
print(h)
print()
print('Array 1 x Array 2')
print(i)

Array 1
[[85 64]
 [13 77]
 [36 21]]

Array 2
[[25 71 79 10]
 [78 11 11 59]]

Array 1 x Array 2
[[7117 6739 7419 4626]
 [6331 1770 1874 4673]
 [2538 2787 3075 1599]]
